apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: talkingdb-release
  title: TalkingDB Release Pipeline
  description: Trigger release + optional docker build for TalkingDB repos
spec:
  type: service
  owner: user:default/mayank.g

  parameters:
    - title: Release Configuration
      properties:
        host_domain:
          type: string
          title: Host Domain

        base_tdb_models_branch:
          type: string
          title: base-tdb-models branch
          default: main

        base_tdb_clients_branch:
          type: string
          title: base-tdb-clients branch
          default: main

        base_tdb_h_helpers_branch:
          type: string
          title: base-tdb-helpers branch
          default: main

        package_content_elementizer_branch:
          type: string
          title: package-content-elementizer branch
          default: main

        module_ttt_branch:
          type: string
          title: module-ttt branch
          default: main

    - title: Docker Configuration
      properties:
        docker_elementizer:
          type: boolean
          title: Build Docker for package-content-elementizer
          default: false

        docker_module_ttt:
          type: boolean
          title: Build Docker for module-ttt
          default: true

        elementizer_tag:
          type: string
          title: package-content-elementizer Docker Tag
          description: Required only if Docker build is enabled

        module_ttt_tag:
          type: string
          title: module-ttt Docker Tag
          description: Required only if Docker build is enabled

  steps:
    - id: trigger
      name: Trigger GitHub Workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=infra-tdb-platform&owner=TalkingDB
        workflowId: sync.yml
        branchOrTagName: main
        workflowInputs:
          host: ${{ parameters.host_domain }}

          repos_json: >
            [
              { "url": "https://github.com/TalkingDB/base-tdb-models.git", "branch": '${{ parameters.base_tdb_models_branch }}' },
              { "url": "https://github.com/TalkingDB/base-tdb-clients.git", "branch": '${{ parameters.base_tdb_clients_branch }}' },
              { "url": "https://github.com/TalkingDB/base-tdb-helpers.git", "branch": '${{ parameters.base_tdb_h_helpers_branch }}' },
              { "url": "https://github.com/TalkingDB/package-content-elementizer.git", "branch": '${{ parameters.package_content_elementizer_branch }}' },
              { "url": "https://github.com/TalkingDB/module-ttt.git", "branch": '${{ parameters.module_ttt_branch }}' },
            ]

          docker_module_ttt: '${{ parameters.docker_module_ttt }}'
          docker_elementizer: '${{ parameters.docker_elementizer }}'

          module_ttt_tag: ${{ parameters.module_ttt_tag }}
          elementizer_tag: ${{ parameters.elementizer_tag }}
  output:
    text:
      - title: Triggered
        content: Release pipeline triggered for ${{ parameters.host_domain }}
