services:
  module-ttt:
    image: talkingdb/ttt
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - tdb-spool:/var/tmp/tdb-spool
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${TTT_BACKEND_HOST}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=le
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8090
    networks:
      - docker

volumes:
  tdb-spool:

networks:
  docker:
    external: true
    name: docker
