name: Sync Repositories

on:
  workflow_call:
    inputs:
      repos_json:
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pyyaml

      - name: Sync repositories
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPOS_JSON: ${{ inputs.repos_json }}
        run: |
          python actions/sync_repositories.py